Introduce Protobuf Message Handling for DRAIN Service.
rancher/opni-drain-service pull request #18
Opened 2022-06-17 21:23 UTC by AmartC

This PR introduces logic to handle Protobuf messages within the Inferencing Service.

2022-06-21 20:26 UTC, tybalex commented on Dockerfile
>  COPY ./drain-service/drain_training_inferencing.py .
copy the dir

2022-07-05 21:16 UTC, dbason commented on Dockerfile
> +RUN pip install opni-aiops-apis==0.5.4
This should be done in the base image

2022-07-07 19:22 UTC, tybalex commented on drain-service/requirements.txt
> +jsonpickle==1.5.1
again, I don't see jsonpickle being used?

2022-07-07 19:34 UTC, sanjay920 requested changes
There are several operations in this code that are inefficient.

There are no pandas related bulk operations executed so there is no need to convert to a data frame. You are looping over each pandas row - the same can be achieved by looping over `PayloadList`

In addition to this when you loop through the df rows, you are:
* converting each row to dict
* adding fields manually by strings to the dict
* adding row dict to list of row dicts

If you loop through `PayloadList`, you can set the payload's fields directly.

2022-07-07 19:48 UTC, AmartC commented on drain-service/requirements.txt
> +jsonpickle==1.5.1
https://github.com/rancher/opni-drain-service/blob/protobuf-drain/drain-service/drain3/template_miner.py#L79
It is used for loading the DRAIN model binary file.

2022-07-12 02:17 UTC, tybalex approved these changes, later dismissed

2022-07-12 05:48 UTC, sanjay920 approved these changes, later dismissed

2022-07-18 23:31 UTC, sanjay920 approved these changes

2022-07-18 23:35 UTC, tybalex approved these changes

2022-07-18 23:50 UTC, merged