Frequent retraining
rancher/opni-drain-service pull request #8
Opened 2021-10-08 20:13 UTC by sanjay920

New environment variable to put frequent retraining behind feature gate: `RETRAIN_OFTEN`

if this env var is not set to "True" then aggressive retraining will remain off

2021-10-08 20:30 UTC, dbason approved these changes

2021-10-08 20:30 UTC, dbason commented on drain-service/drain_training_inferencing.py
> +        RETRAIN_OFTEN = False
Should normalize the case, and can also simplify this statement:
```
RETRAIN_OFTEN = os.environ["RETRAIN_OFTEN"].lower() == "true"
```

2021-10-08 20:30 UTC, dbason requested changes
See comment

2021-10-08 20:41 UTC, dbason approved these changes

2021-10-09 01:01 UTC, AmartC approved these changes

2021-10-09 01:01 UTC, merged